version: 2

project_name: chiffremento

before:
  hooks:
    - go mod tidy

release:
  header: |
    # 🎉 v1.1.0 - Streaming & UX Automatisée

    Cette version v1.1.0 apporte une refonte majeure du moteur d'entrées/sorties (Streaming SIO) et simplifie considérablement l'utilisation quotidienne (Extension `.chto` automatique).

    ## 🚀 Nouveautés Principales

    ### ⚡ Mode Streaming (Memoire Constante)
    *   **Fini les limites de RAM :** Chiffremento n'utilise plus `os.ReadFile`. Il utilise désormais des flux (`io.Reader`/`io.Writer`) via la librairie sécurisée `minio/sio`.
    *   **Performance :** Chiffrer un fichier de 10 Go ne consomme que quelques méga-octets de RAM.

    ### 🎮 UX & Automatisaton
    *   **Extension `.chto` imposée :** Plus d'erreur possible. Les fichiers chiffrés ont toujours l'extension `.chto`. Le déchiffrement refuse tout autre fichier.
    *   **Suppression du flag `-out` :** Le nom de sortie est déduit automatiquement (ex: `doc.pdf` -> `doc.pdf.chto` -> `doc.pdf`).
    *   **Fail Fast :** Validation immédiate des arguments et extensions.

    ### 🛡️ Sécurité & Robustesse
    *   **Anti-DoS Récursif :** Protection contre les fichiers malveillants imbriquant des headers en boucle infinie.
    *   **Dérivation HKDF (Mode Parano) :** En mode cascade, les clés AES et ChaCha sont désormais dérivées indépendamment via HKDF.
    *   **Tripwire :** Tests unitaires qui échouent si le protocole binaire change silencieusement.

    ### 🇫🇷 Harmonisation
    *   **100% Français :** Tous les logs, erreurs et commentaires techniques ont été standardisés en français.

    ---

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: ValMtp3
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"

    directory: Formula
    homepage: "https://github.com/valentinfiess/chiffremento-go-cli"
    description: "Outil de chiffrement CLI sécurisé et robuste en Go"
    license: "MIT"
    test: |
      system "#{bin}/chiffremento -version"
